### ISSUE TITLE
about interpolation

### ISSUE THREAD

**Issue by Winnie202** [llmpass/RSTT#10]
I trained my own dataset, but the effect of interpolation  is not good. If I do not want to interpolation frames, that is, input_ frame=4,output_ frame=4, how should I modify it?
can i modify the output_frame in the weight of completed training?

**Comment by llmpass** [comment]
You may also need to modify the positional encoding part, otherwise it will not work.

**Comment by Winnie202** [comment]
> You may also need to modify the positional encoding part, otherwise it will not work.

Excuse me, which parts of the code are modified

**Comment by llmpass** [comment]
> > You may also need to modify the positional encoding part, otherwise it will not work.
> 
> Excuse me, which parts of the code are modified

https://github.com/llmpass/RSTT/issues/10#issuecomment-1365546755

**Comment by llmpass** [comment]
> > You may also need to modify the positional encoding part, otherwise it will not work.
> 
> Excuse me, which parts of the code are modified

https://github.com/llmpass/RSTT/blob/b10988958137cc9fa8a2b814f0f94c4900d736fc/models/layers.py#L163

**Comment by Winnie202** [comment]
> > > You may also need to modify the positional encoding part, otherwise it will not work.
> > 
> > 
> > Excuse me, which parts of the code are modified
> 
> https://github.com/llmpass/RSTT/blob/b10988958137cc9fa8a2b814f0f94c4900d736fc/models/layers.py#L163

Excuse me, don't you need to modify the output sequence length? Because out_ frames is defined here,I'm confused about this
![2022-12-27 14-01-24屏幕截图](https://user-images.githubusercontent.com/86768013/209619361-27aa939f-a823-4a30-a0f6-c67ba2304b8a.png)

**Comment by llmpass** [comment]
> > > > You may also need to modify the positional encoding part, otherwise it will not work.
> > > 
> > > 
> > > Excuse me, which parts of the code are modified
> > 
> > 
> > https://github.com/llmpass/RSTT/blob/b10988958137cc9fa8a2b814f0f94c4900d736fc/models/layers.py#L163
> 
> Excuse me, don't i need to modify the output sequence length at the following code section? Because num_out_frames is defined here,I'm confused about this,because I don't need to change the size of the output feature map, I just need to modify it num_out_frames same as num_input_frames ![2022-12-27 14-01-24屏幕截图](https://user-images.githubusercontent.com/86768013/209619361-27aa939f-a823-4a30-a0f6-c67ba2304b8a.png)

yes.

**Comment by Winnie202** [comment]
> > > > > You may also need to modify the positional encoding part, otherwise it will not work.
> > > > 
> > > > 
> > > > Excuse me, which parts of the code are modified
> > > 
> > > 
> > > https://github.com/llmpass/RSTT/blob/b10988958137cc9fa8a2b814f0f94c4900d736fc/models/layers.py#L163
> > 
> > 
> > Excuse me, don't i need to modify the output sequence length at the following code section? Because num_out_frames is defined here,I'm confused about this,because I don't need to change the size of the output feature map, I just need to modify it num_out_frames same as num_input_frames ![2022-12-27 14-01-24屏幕截图](https://user-images.githubusercontent.com/86768013/209619361-27aa939f-a823-4a30-a0f6-c67ba2304b8a.png)
> 
> yes.

if  I don't need to change the size of the output feature map, I just need to modify it num_out_frames same as num_input_frames,does the following code section need change

**Comment by llmpass** [comment]
> > > > > > You may also need to modify the positional encoding part, otherwise it will not work.
> > > > > 
> > > > > 
> > > > > Excuse me, which parts of the code are modified
> > > > 
> > > > 
> > > > https://github.com/llmpass/RSTT/blob/b10988958137cc9fa8a2b814f0f94c4900d736fc/models/layers.py#L163
> > > 
> > > 
> > > Excuse me, don't i need to modify the output sequence length at the following code section? Because num_out_frames is defined here,I'm confused about this,because I don't need to change the size of the output feature map, I just need to modify it num_out_frames same as num_input_frames ![2022-12-27 14-01-24屏幕截图](https://user-images.githubusercontent.com/86768013/209619361-27aa939f-a823-4a30-a0f6-c67ba2304b8a.png)
> > 
> > 
> > yes.
> 
> if I don't need to change the size of the output feature map, I just need to modify it num_out_frames same as num_input_frames,does the following code section need change
> 
> ![2022-12-27 15-04-59屏幕截图](https://user-images.githubusercontent.com/86768013/209626282-3593f22b-ef6c-4789-aaf2-d13840a07602.png)

You are right.
