### ISSUE TITLE
Train on myself datasets

### ISSUE THREAD

**Issue by jackxx33** [llmpass/RSTT#4]
Hello,I am very interested in your work. I want to use this model to train my own dataset,is this possible?

**Comment by jackxx33** [comment]
Does this model have to 4 frame input 7 frame output? Can I change some places to achieve 2x or 3x frame interpolation? And why the num_frames in 'RSTT-S.yml' is 7 instead of 4? Thanks!

**Comment by llmpass** [comment]
Yes. It can achieve 2x or 3x frame interpolation, but you have to change the code to feed the right number of output frames. Then, change the code starts at https://github.com/llmpass/RSTT/blob/9a27232d7066a545cd026d24b8c987e73e69c76f/models/RSTT.py#L145.
