### ISSUE TITLE
about train config

### ISSUE THREAD

**Issue by Winnie202** [llmpass/RSTT#8]
Excuse me, I am training my own super resolution data. The HR_image size is 720 * 1080. What relevant parameter settings need to be changed?crop_size need to change the size to 720?

![2022-12-14 10-32-41屏幕截图](https://user-images.githubusercontent.com/86768013/207490972-dfabf762-f4ac-45f7-b072-36452e1416dc.png)

**Comment by llmpass** [comment]
Hi, if your amplify factor is still 4 (on both width and height), you should set it to [3, 180, 270].

**Comment by Winnie202** [comment]
> Hi, your setting is correct. Probably, you can keep the crop size as 256.

Thank you for your reply. In addition, the size of my training data image format is 8GB. After the "create_lmdb.py"  is converted to lmdb, but the size is close to 80GB. Is this normal?

**Comment by llmpass** [comment]
> > Hi, your setting is correct. Probably, you can keep the crop size as 256.
> 
> Thank you for your reply. In addition, the size of my training data image format is 8GB. After the "create_lmdb.py" is converted to lmdb, but the size is close to 80GB. Is this normal?

Please don't just use the file size to judge if the process is correct or not. I think a better way is to write a piece of code, for example a notebook to check if the entries in this lmdb is what you expected or not.

**Comment by Winnie202** [comment]
> > > Hi, your setting is correct. Probably, you can keep the crop size as 256.
> > 
> > 
> > Thank you for your reply. In addition, the size of my training data image format is 8GB. After the "create_lmdb.py" is converted to lmdb, but the size is close to 80GB. Is this normal?
> 
> Please don't just use the file size to judge if the process is correct or not. I think a better way is to write a piece of code, for example a notebook to check if the entries in this lmdb is what you expected or not.

Yes, I have verified that the content in the lmdb is correct, but the file becomes too large after being converted to the lmdb format, and my computer does not have enough space. I wonder if this is normal

**Comment by llmpass** [comment]
> > > > Hi, your setting is correct. Probably, you can keep the crop size as 256.
> > > 
> > > 
> > > Thank you for your reply. In addition, the size of my training data image format is 8GB. After the "create_lmdb.py" is converted to lmdb, but the size is close to 80GB. Is this normal?
> > 
> > 
> > Please don't just use the file size to judge if the process is correct or not. I think a better way is to write a piece of code, for example a notebook to check if the entries in this lmdb is what you expected or not.
> 
> Yes, I have verified that the content in the lmdb is correct, but the file becomes too large after being converted to the lmdb format, and my computer does not have enough space. I wonder if this is normal

If this is the case, probably you can reduce the number of entries.
